services:
  app:
    build: 
      context: .
      dockerfile: dockerfile
    restart: always
    env_file:
      - .env
    ports:
      - ${PORT}:3000
    depends_on:
      - redis 
    volumes:
      - .:/app
    networks:
      - app
    command: sh -c "npm run build && npm run start"
    

  redis:
    image: redis
    restart: always
    ports:
      - ${REDIS_PORT}:6379
    networks:
      - app
    volumes:
      - db:/data


volumes:
  app:
  db:

networks:
  app:
    driver: bridge